### ISSUE TITLE
provide golang infrastructure for pre-commit

### ISSUE THREAD

**Issue by goern** [thoth-station/zuul-test-infra#38]
Let's merge https://github.com/larsks/opf-go-precommit and thoth-precommit from https://github.com/thoth-station/thoth-ops-infra in one container image, so that we can have a unified pre-commit job (for example https://github.com/thoth-station/slo-reporter/blob/master/.prow.yaml#L2-L13) for python or golang source

seeAlso https://operatefirst.slack.com/archives/C01RF4SPNDD/p1622570329014400

/assign @harshad16 
/assign @larsks 
/priority important-soon
/sig pipelines
/area documentation

**Comment by larsks** [comment]
The existing pre-commit images are based on images from the [s2i-thoth](https://github.com/thoth-station/s2i-thoth) repository. If we want a f34/py39 based pre-commit image, do we need to start with `f34-py39` image in `s2i-thoth`?

**Comment by harshad16** [comment]
it will be there in few mins , we are releasing it

**Comment by larsks** [comment]
The existing pre-commit images set `$HOME` to `/opt/app-root/src`, which is presumably where one is expected to mount the source tree to be checked. This is a bad default, since it means anything that normally gets installed in `$HOME` gets installed into the source tree, which can have unintended side effects (this is a particularly problem with Go, because it will by default install dependencies into `~/go`, so running `go test ./...` in the source tree will pick up unit tests for all the dependencies).

When running on a local system, changes in `/opt/app-root/src` impact the local build environment, since the source tree is bind-mounted into the image.

We need make `$HOME` different from the source tree.

I guess the easiest option is just to mount the sources somewhere else at runtime, e.g.:

```
docker run -v $PWD:/src -w /src ...
```

**Comment by goern** [comment]
What is the behaviour implemented by s2i-go ?

**Comment by larsks** [comment]
I haven't the foggiest idea. Taking a look at https://github.com/sclorg/golang-container now...

**Comment by larsks** [comment]
The go s2i image sets HOME to /opt/app-root/src, but the Dockerfile generated by `s2i build --as-dockerfile ...` copies sources into `/tmp/src` and runs the build from there:

```
pushd /tmp/src
[...]
go build -o /opt/app-root/gobinary
```
